name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
  
  windows_build:
    
    runs_on: windows-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run Tests
      run: cargo test --release --verbose
